language: node_js

node_js:
    - node

jobs:
  include:
    - stage: unit tests
    - script: echo "npm run test:unit"
    - stage: build library
    - script: npm run build:lib
    - stage: build docs
    - script: npm run build:docs
    - stage: deploy docs
    - script: npm run build:docs
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $VUE_TRANSITION_GITHUB_TRAVIS
        keep_history: true
        local_dir: dist/docs
        on:
          branch: main
