language: node_js

node_js:
    - node

jobs:
  include:
    - stage: test
      script: echo "npm run test:unit"
    - stage: build library
      script: npm run build:lib
    - stage: build docs
      script: npm run build-storybook
    - stage: deploy docs
      script: skip
      deploy:
        provider: pages
        script: npm run build
        cleanup: true
        token: $VUE_TRANSITION_GITHUB_TRAVIS
        keep_history: true
        local_dir: dist/docs
          on:
            branch: main
